# Home Manager module — renders the niri window-animation KDL fragment
# (durations + custom-shader bodies) and drops it at
# ~/.config/niri-shaders/animations.kdl via xdg.configFile.
#
# The consuming niri config includes it with niri's native `include`
# directive instead of embedding the GLSL inline:
#
#   include "~/.config/niri-shaders/animations.kdl" optional=true

{ config, lib, pkgs, ... }:

let
  cfg = config.programs.niri.shaders;

  # niriPkg is accepted for a possible future readNiriShaderCompileInfo call
  # but unused by the assembly path itself — null is fine (see niri-shaders.nix).
  shaders = import ./niri-shaders.nix {
    inherit pkgs;
    niriPkg = null;
    shaderProfile = cfg.shaderProfile;
  };

  animationsKdl = ''
    // Generated by niri-shaders (github:mikenrafter/niri-shaders) —
    // do not edit by hand.
    animations {
        window-open {
            duration-ms ${toString shaders.durations.windowOpen}
            curve "linear"

            custom-shader r#"${shaders.windowOpen}"#
        }

        window-close {
            duration-ms ${toString shaders.durations.windowClose}
            curve "linear"

            custom-shader r#"${shaders.windowClose}"#
        }

        window-resize {
            duration-ms ${toString shaders.durations.windowResize}
            curve "linear"

            custom-shader r#"${shaders.windowResize}"#
        }
    }
  '';
in
{
  options.programs.niri.shaders = {
    enable = lib.mkEnableOption "niri custom-shader window animations";

    shaderProfile = lib.mkOption {
      type = lib.types.str;
      default = "full";
      description = ''
        Shader profile name from niri-shader-anims.nix:
        - "full" — unhook + shredder + voronoi close; ngon + voronoi open
        - "simple" — unhook + shredder close; ngon open
        - "unhook-only" / "shredder-only" / "voronoi-only" — showcase singles
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile."niri-shaders/animations.kdl".text = animationsKdl;
  };
}
